
from . import failure_static, fatigue, beam, torsion, shafts_design, bolts, welds, springs, bearings, gears_agma, pressure_vessels, fits, clutches_brakes, belts, buckling, shaft_analysis, power_screw
REGISTRY = {
  "failure.von_mises": failure_static.von_mises,
  "failure.tresca": failure_static.tresca,
  "fatigue.endurance_modified": fatigue.endurance_modified,
  "fatigue.goodman": fatigue.goodman,
  "fatigue.gerber": fatigue.gerber,
  "fatigue.soderberg": fatigue.soderberg,
  "shaft.design.d_required_fatigue": fatigue.shaft_required_d,
  "shaft.design.d_required_static": shafts_design.diameter_static,
  "beam.eb.simply_supported.udl": beam.simply_supported_udl,
  "beam.eb.simply_supported.point_mid": beam.simply_supported_point_mid,
  "beam.cantilever.point_end": beam.cantilever_point_end,
  "shaft.torsion.solid": torsion.solid,
  "shaft.torsion.hollow": torsion.hollow,
  "bolt.preload_proof": bolts.preload_proof,
  "weld.fillet.linear": welds.fillet_linear,
  "shaft.analysis.segmented": shaft_analysis.shaft_segmented,
  "spring.helical.compression": springs.helical_compression,
  "spring.helical.extension": springs.helical_extension,
  "spring.helical.torsion": springs.helical_torsion,
  "spring.helical.parallel": springs.concentric_parallel,
  "bearing.ball.L10": bearings.L10,
  "bearing.ball.life_reliability": bearings.life_with_reliability,
  "bearing.ball.required_C": bearings.required_rating,
  "bearing.ball.equivalent_load": bearings.equivalent_dynamic_load,
  "gear.spur.agma_bending_basic": gears_agma.spur_bending_basic,
  "gear.spur.agma_contact_basic": gears_agma.spur_contact_basic,
  "pv.cylinder.thin": pressure_vessels.thin_cylinder,
  "pv.cylinder.thick": pressure_vessels.thick_cylinder_lame,
  "fit.press.interference": fits.press_fit,
  "clutch.single_disc.uniform_pressure": clutches_brakes.single_disc_uniform_pressure,
  "clutch.single_disc.uniform_wear": clutches_brakes.single_disc_uniform_wear,
  "belt.flat.power": belts.flat_belt_power,
  "belt.flat.tension_ratio": belts.tension_ratio,
  "column.euler": buckling.euler,
  "column.johnson": buckling.johnson_parabolic,
  "power.screw.raise": power_screw.power_screw,
}
